os: osx
language: node_js
branches:
  only:
    - master
    - feature/onboarding
jobs:
  include:
    - stage: Code Quality
      script: yarn lint
    - stage: Tests
      script: yarn test:unit
    - stage: Build
      script: yarn electron:build